### PR TITLE
Added a note for the changed UI while creating a new Tenant

### PR DESCRIPTION
**Pull request by DieterRauscher**
# Module: 00
## Lab/Demo: 00

Fixes # .

Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by polichtm** [comment]
Hi Dieter,
can you clarify what you mean by "preview version"?
rgds
Marcin

**Comment by DieterRauscher** [comment]
Hi Marcin,

Sure:
It depends on your “Preview feature” configuration. If I am not mistaken now the default looks like this:

***@***.***D75200.A1D4E280]

So there’s no “Create Tenant” option, but a “Manage tenants” one.


You can change back to the “non-preview” version by selecting “Preview features” and turn it off.
***@***.***D75200.A1D4E280]


Only then you see the “Create a tenant” option:
***@***.***D75200.A1D4E280]

Hope this helps!

Dieter

**Comment by polichtm** [comment]
Hi Dieter,
unfortunately it's still not clear to me what you're referring to. What is this preview of?
rgds
Marcin

**Comment by polichtm** [comment]
Closing due to lack of response - the option to Create tenant is available in a generic Azure Pass subscription:
image

rgds
Marcin

**Pull request closed without merging**
