### PR TITLE
Outbound to Inbound

### PR DESCRIPTION
**Pull request by jaguiber**
On line 157 changed Task 3, step 12. A Typo. "On the myNsgPrivate | Outbound security rules blade..."  Should be the Inbound not Outbound

# Module: 00
## Lab/Demo: 00

Fixes # .

Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by polichtm** [comment]
Hi Jacques,
would you mind clarifying what is the purpose of clicking Inbound security rules if you are already on the blade showing Inbound security rules?
rgds
Marcin

**Comment by jaguiber** [comment]
The instructions seem to confuse our learners, on line 157, they actually need to switch from outbound to inbound rules for this step.

Thanks,

Jacques Guibert De Bruet
Azure Technical Trainer
________________________________

**Comment by polichtm** [comment]
Hi Jacques,
As far as I can tell, the instructions are correct. You are at that point on the **myNsgPrivate \| Outbound security rules** blade and you are clicking **Inbound security rules**.

It appears that what you are suggesting is incorrect. There is no point of clicking **Inbound security rules** if you are already on the **myNsgPrivate \| Intbound security rules** blade (which, btw. at that point, you are not)

Hope this makes sense.

rgds
Marcin

**Comment by jaguiber** [comment]
Understood, please discard the pull request.

Thanks,

Jacques Guibert De Bruet
Azure Technical Trainer
________________________________

**Pull request closed without merging**
